main.o: main.c def.h /usr/include/luajit-2.1/lua.h \
 /usr/include/luajit-2.1/luaconf.h /usr/include/luajit-2.1/lualib.h \
 /usr/include/luajit-2.1/lua.h /usr/include/luajit-2.1/lauxlib.h
bitmap.o: bitmap.c bitmap.h def.h
fhk_graph.o: fhk_graph.c bitmap.h def.h fhk.h arena.h type.h grid.h
fhk_solve.o: fhk_solve.c def.h fhk.h bitmap.h arena.h type.h grid.h
fhk_aux.o: fhk_aux.c fhk.h bitmap.h def.h arena.h type.h grid.h
type.o: type.c type.h grid.h bitmap.h def.h
arena.o: arena.c def.h arena.h
sim.o: sim.c arena.h def.h sim.h
sim_ds.o: sim_ds.c sim.h sim_ds.h grid.h bitmap.h def.h vec.h
grid.o: grid.c grid.h bitmap.h def.h
vec.o: vec.c vec.h
gmap.o: gmap.c gmap.h fhk.h bitmap.h def.h arena.h type.h grid.h model.h \
 vec.h sim_ds.h sim.h
vmath.o: vmath.c vmath.h def.h
model_aux.o: model_aux.c model.h type.h grid.h bitmap.h def.h list.h
model_R.o: model_R.c model.h type.h grid.h bitmap.h def.h model_aux.h \
 model_R.h
model_SimoC.o: model_SimoC.c model.h type.h grid.h bitmap.h def.h \
 model_aux.h model_SimoC.h
lua/m2_cdef.lua: lua_exports.h type.h grid.h bitmap.h def.h sim.h \
 sim_ds.h vec.h fhk.h arena.h gmap.h model.h vmath.h model_all.h \
 model_R.h model_aux.h model_SimoC.h
